Run tests on ubuntu-20.04 instead of ubuntu-18.04
Running node 18 on ubuntu-18.04 gives us the error below:

```
/opt/hostedtoolcache/node/18.1.0/x64/bin/node --version
/opt/hostedtoolcache/node/18.1.0/x64/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/hostedtoolcache/node/18.1.0/x64/bin/node)
Error: The process '/opt/hostedtoolcache/node/18.1.0/x64/bin/node' failed with exit code 1
```

Hopefully upgrading ubuntu will give us a new enough libc that this
error will go away.